package com.hellolaw.hellolaw.entity;

public enum Category {
	STAKING,
	SEX_CRIME,
	TRAFFIC_ACCIDENT_AND_DRINKING_DRIVING,
	ASSAULT_AND_INJURY,
	DRUGS,
	FRAUD,
	DIVORCE,
	INHERITANCE_AND_HOUSEHOLD,
	LOAN_AND_UNPAID_AND_BOND_COLLECTION,
	ADMINISTRATIVE_LITIGATION,
	CONSUMER_DISPUTES,
	OTHER;
}
